### ISSUE TITLE
why we have "--package test" as parameter of eclat.py ??

### ISSUE THREAD

**Issue by StefanoSalsano** [netgroup/eclat-daemon#52]

**Comment by lorenzobracciale** [comment]
As we decided that programs, loaders and chains got name and package. Chains potentially can thus be included in a package. If we run the chain starting from an eCLAT file, we use the chain name for its name but for the package name we ask the user with the CLI.
Perhaps we can introduce a default value for that or use something else (e.g. the file name)?

**Comment by lorenzobracciale** [comment]
We set a default
