### ISSUE TITLE
add -fetch_pkg to eclat.py

### ISSUE THREAD

**Issue by StefanoSalsano** [netgroup/eclat-daemon#57]
this command is used to clone the repository of a package

eclat.py -fetch_pkg package_name

the main reason is that we want to keep the eclat scripts of a package inside the package folders
and also the shell scripts to run the testbed

**Comment by lorenzobracciale** [comment]
add doc to https://github.com/hike-eclat/docs/blob/master/docs/eclat_doc.rst

**Comment by lorenzobracciale** [comment]
All done in 7a6e75dd23f0917dbb4fce7b92fe5196e47f7251 
Updated docs with the commands (but you can see the new ones by `python eclat.py -h`)

@StefanoSalsano please check before merging into the master

**Comment by lorenzobracciale** [comment]
Test works

**Comment by StefanoSalsano** [comment]
fetch-pkg is not working

ho provato
python eclat.py fetch-pkg $MY_PACKAGE

non andava... ho fixato un po di cose in eclat.py

ma poi sono arrivato ad un punto in cui manca qualche pezzo in
eclat_pb2_grpc.EclatStub


  File "/opt/eclat-daemon/eclat.py", line 84, in fetch_pkg
    response = stub.FetchPackageConfiguration(req)
AttributeError: 'EclatStub' object has no attribute 'FetchPackageConfiguration'
